from datetime import  time, timedelta

# Booking status
BOOKING_STATUS_CONFIRMED = 1
BOOKING_STATUS_CANCELLED = 2
BOOKING_STATUS_CHOICES = (
    (BOOKING_STATUS_CONFIRMED, 'Confirmed'),
    (BOOKING_STATUS_CANCELLED, 'Cancelled'),
)

BOOKING_STATUS_LABELS = {
    BOOKING_STATUS_CONFIRMED: 'confirmed',
    BOOKING_STATUS_CANCELLED: 'cancelled',
}

# Idempotency
IDEMPOTENCY_IN_PROGRESS = 1
IDEMPOTENCY_COMPLETED = 2
IDEMPOTENCY_STATUS_CHOICES = (
    (IDEMPOTENCY_IN_PROGRESS, 'In Progress'),
    (IDEMPOTENCY_COMPLETED, 'Completed'),
)

# Booking rules
MIN_BOOKING_DURATION_MINUTES = 15
MAX_BOOKING_DURATION_HOURS = 4
BUSINESS_START_HOUR = 8
BUSINESS_END_HOUR = 20
BUSINESS_WEEKDAYS = (0, 1, 2, 3, 4)
CANCELLATION_CUTOFF_HOURS = 1

# Pagination
DEFAULT_PAGE_LIMIT = 20
MAX_PAGE_LIMIT = 200

#business const
MIN_DURATION = timedelta(minutes=MIN_BOOKING_DURATION_MINUTES)
MAX_DURATION = timedelta(hours=MAX_BOOKING_DURATION_HOURS)

BUSINESS_START = time(BUSINESS_START_HOUR, 0)
BUSINESS_END = time(BUSINESS_END_HOUR, 0)
